<tr>
	<td><a href='/bug/edit/id/<?php echo $this->id;?>' title="<?php echo $this->translate('Edit'); ?>"><?php echo $this->translate('Edit'); ?></a> |
	<a href='/bug/delete/id/<?php echo $this->id;?>' title="<?php echo $this->translate('Delete'); ?>"><?php echo $this->translate('Delete'); ?></a></td>
	<td><?php echo date('m/d/y', $this->date); ?></td>
	<td><?php echo $this->priority; ?></td>
	<td><?php echo $this->status; ?></td>
	<td><?php echo $this->url; ?></td>
	<td><?php echo $this->author; ?></td>
	<td><?php echo $this->description; ?></td>
</tr>