<?php
	$this->headTitle()->prepend($this->translate('Proyectos Evaluados :: ')); 
?>
<div class="row-fluid">	
	<div class="span12">
		<?php					
			if(count($this->messages) > 0 && $this->referer == 'project')
				printf("<div id='flash'>%s</div>", $this->messages[0]);			
		?>
		<section class="proyects">
			<h2><?php echo $this->translate('Proyectos evaluados'); ?></h2>		

			<?php echo $this->form_filter_projects; ?>	
			
	        <?php if (count($this->paginator) > 0): ?>			
				<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/_pagination.phtml'); ?>
				<?php foreach($this->paginator AS $project): ?>
					<article class="other-proyects <?php if($project->completed) echo "green"; ?>">
						<header class="header-project">
							<div class="row-fluid">
								<div class="span4">
									<span class="name"><h3><?php echo $project->nombre_del_proyecto; ?></h3></span>
								</div>
								<div class="span6">	
									<span class="category">
										<?php echo $this->translate('Categoría: '); ?>
										<?php echo $project->uso_principal_del_edificio; ?>
									</span>
									<span class="place">
										<?php echo $this->translate('Lugar: '); ?>
										<?php echo $project->lugar; ?>
									</span>
								</div>
								<div class="span2">
									<?php if($project->completed): ?>
										<div class="state complete"><?php echo $this->translate('Proyecto completo'); ?></div>
									<?php else: ?>
										<div class="state incomplete"><?php echo $this->translate('Proyecto incompleto'); ?></div>
									<?php endif; ?>	
								</div>
							</div>
						</header>
						<div class="row-fluid">
		                	<div class="span4">
								<div class="picture">
								<?php if($project->photo): ?>
									<img src="<?php echo $this->serverUrl() . Zend_Registry::get('config')->paths->frontend->images . 'projects/' .  $project->photo; ?>" width="" height="" alt="">
								<?php else: ?>
									<img src="<?php echo $this->serverUrl() . Zend_Registry::get('config')->paths->frontend->images . '150x100.gif'; ?>" width="150" height="100" alt="">
								<?php endif; ?>	
								</div>
								<div class="graphic">
									<img src="<?php echo $this->serverUrl() . Zend_Registry::get('config')->paths->frontend->images . 'graphs/' .  $project->s_photo; ?>" width="" height="" alt="">
								</div>
							</div>
		                    <div class="span8">
		                        <div class="description">
									<p><?php echo $project->breve_descripcion; ?></p>
									<div class="botons">		
										<a href="<?php echo $this->url(array('controller' => 'report', 'project_id' => $project->id), 'reportRoute'); ?>" title="<?php echo $this->translate('Ver informe'); ?>"><?php echo $this->translate('Ver informe'); ?></a>
									</div>
								</div>
							</div>
						</div>
					</article>						
				<?php endforeach; ?>
			<?php else: ?>
				<?php echo $this->translate('No hay proyectos'); ?>
			<?php endif; ?> 
		</section>	
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/projects-evaluated/main.js'; ?>"></script>