<form id="bug" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
	<?php echo $this->element->id; ?>
	<?php echo $this->element->name; ?>
	<?php echo $this->element->email; ?>	
	<?php echo $this->element->subject; ?>
	<?php echo $this->element->message; ?>
	<?php echo $this->element->csrfVerification; ?>
	<?php echo $this->element->submit; ?>
</form>