<?php
	// get instance of view 
	$view = Zend_Layout::getMvcInstance()->getView(); 
?>
<?php 
	// load in object session fields aplicable si/no from database
	$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    $myNamespace->{'aplicable_' . $view->project_id . 'mp3'} = $view->fieldsAplicable;
?>
<form class="<?php echo $this->element->getAttrib('class'); ?>" id="<?php echo $this->element->getAttrib('id'); ?>" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
	<table class="forms">
		<tr class="<?php if($view->fieldsAplicable[1]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
			<td class="column1">x</td>   				  
			<?php echo $this->element->evapotranspiracion_real; ?>	
			<td class="column4"><?php echo $view->units[1]; ?></td>
		</tr>
		<tr class="<?php if($view->fieldsAplicable[2]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
			<td class="column1">x</td>   				  
			<?php echo $this->element->evapotranspiracion_potencial; ?>	
			<td class="column4"><?php echo $view->units[2]; ?></td>
		</tr>
		<tr class="<?php if($view->fieldsAplicable[3]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
			<td class="column1">x</td>   				  
			<?php echo $this->element->humedad_del_suelo; ?>	
			<td class="column4"><?php echo $view->units[3]; ?></td>
		</tr>
		<tr class="<?php if($view->fieldsAplicable[4]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
			<td class="column1">x</td>   				  
			<?php echo $this->element->escorrentias_zonas_vulnerables; ?>	
			<td class="column4"><?php echo $view->units[4]; ?></td>
		</tr>
		<tr class="<?php if($view->fieldsAplicable[5]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
			<td class="column1">x</td>   				  
			<?php echo $this->element->escorrentias_zonas_sensibles; ?>	
			<td class="column4"><?php echo $view->units[5]; ?></td>
		</tr>
		<tr class="<?php if($view->fieldsAplicable[6]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
			<td class="column1">x</td>   				  
			<?php echo $this->element->escorrentias_zona_de_captacion_de_zona_sensible; ?>	
			<td class="column4"><?php echo $view->units[6]; ?></td>
		</tr>
		<tr class="<?php if($view->fieldsAplicable[7]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
			<td class="column1">x</td>   				  
			<?php echo $this->element->permeabilidad; ?>	
			<td class="column4"><?php echo $view->units[7]; ?></td>
		</tr>
	</table>
	<span class="not-applicable"><?php echo $this->translate('Pinche sobre la x si no procede.'); ?></span>	
	<?php echo $this->partial('partials/_form_navigation.phtml', array('attribs' => $this->element->getAttrib('id'), 'prev' => true, 'next' => true, 'prev_s' => null, 'next_s' => null)); ?>
	<?php echo $this->element->submit; ?>
	<div class="clr"></div>	
	<label><?php echo $this->translate('Comentarios y especificaciones para la valoración'); ?></label>
    <?php echo $this->element->comentarios; ?>	
</form>