<?php 
	$view = Zend_Layout::getMvcInstance()->getView(); 
?>
<?php 
	// load in object session fields aplicable si/no from database
	$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    $myNamespace->{'aplicable_' . $view->project_id . 'bl2'} = $view->fieldsAplicable;
?>
<form class="<?php echo $this->element->getAttrib('class'); ?> re" id="<?php echo $this->element->getAttrib('id'); ?>" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
	<table class="forms">
		<thead>
			<tr><th colspan="3">&nbsp</th></tr>
		</thead>
		<tbody>	
			<tr class="<?php if($view->fieldsAplicable[1]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
				<td class="column1">x</td>   				  
					<?php echo $this->element->factor_luz_dia; ?>
				<td class="column4"><?php echo $view->units[1]; ?></td>
			</tr>
			<tr class="<?php if($view->fieldsAplicable[2]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
				<td class="column1">x</td>   				  
					<?php echo $this->element->control_de_sistemas_de_sombreamiento; ?>
				<td class="column4"><?php echo $view->units[2]; ?></td>
			</tr>
			<tr class="<?php if($view->fieldsAplicable[3]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
				<td class="column1">x</td>   				  
					<?php echo $this->element->acceso_solar_en_estancias_principales; ?>
				<td class="column4"><?php echo $view->units[3]; ?></td>
			</tr>
			<tr class="<?php if($view->fieldsAplicable[4]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
				<td class="column1">x</td>   				  
					<?php echo $this->element->linea_visual_profundidad; ?>
				<td class="column4"><?php echo $view->units[4]; ?></td>
			</tr>
			<tr class="<?php if($view->fieldsAplicable[5]) { echo "aplicable-si"; } else { echo "aplicable-no";  } ?>">
				<td class="column1">x</td>   				  
					<?php echo $this->element->confort_acustico_atenuacion_de_ruido; ?>
				<td class="column4"><?php echo $view->units[5]; ?></td>
			</tr>		
		</tbody>	
	</table>
	<span class="not-applicable"><?php echo $this->translate('Pinche sobre la x si no procede.'); ?></span>	
	<?php echo $this->partial('partials/_form_navigation.phtml', array('attribs' => $this->element->getAttrib('id'), 'prev' => true, 'next' => true, 'prev_s' => null, 'next_s' => null)); ?>	
	<div class="clr"></div>	
	<label><?php echo $this->translate('Comentarios y especificaciones para la valoración'); ?></label>
    <?php echo $this->element->comentarios; ?>
</form>