<?php
	$this->headTitle()->prepend($this->translate('Listado usuarios :: ')); 
?>
<?php echo $this->partial('partials/_admin_menu.phtml'); ?>
<?php if($this->messages || $this->errors): ?>
<div class="row-fluid">
	<div class="span5">
		<?php $this->successMessages($this->messages); ?>	
		<?php $this->errorMessages($this->errors); ?>		
	</div><!-- .span5 -->
	<div class="span7">	            
	</div><!-- .span7 -->
</div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">	
	<div class="span12">
		<h2><?php echo $this->translate('Estádisticas'); ?></h2>
	</div>
</div>
<div class="row-fluid">	
	<div class="span12">
		<h2><?php echo $this->translate('Usuarios actuales'); ?></h2>
		<?php if($this->paginator != null): ?>
		<table class='spreadsheet' cellpadding='3' cellspacing='0'>
			<tr>
				<th><?php echo $this->translate('Foto'); ?></th>
				<th><?php echo $this->translate('Usuario'); ?></th>	
				<th><?php echo $this->translate('Apellido'); ?></th>
				<th><?php echo $this->translate('Nombre'); ?></th>				
				<th><?php echo $this->translate('Role'); ?></th>
				<th><?php echo $this->translate('Proyectos'); ?></th>
				<th><?php echo $this->translate('Proyects Públicos'); ?></th>
				<th><?php echo $this->translate('Proyectos Privados'); ?></th>
				<th><?php echo $this->translate('Enlaces'); ?></th>
			</tr>
			<?php echo $this->partialLoop('partials/_user_row.phtml', $this->paginator); ?>
			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/_pagination.phtml'); ?>
		</table>
		<?php else: ?>
			<p><?php echo $this->translate('No hay ningún usuario.'); ?></p>
		<?php endif; ?>
		<p>
			<a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'register'), 'accountRoute'); ?>" title="<?php echo $this->translate('Crear un nuevo usuario'); ?>" title="<?php echo $this->translate('Crear un nuevo usuario'); ?>"><?php echo $this->translate('Crear un nuevo usuario'); ?></a>
		</p>
	</div><!-- .span12 -->	
</div><!-- .row-fluid -->