<?php
	$this->headTitle()->prepend($this->translate('Registro usuario :: ')); 
?>
<div class="row-fluid">
	<div class="span5">
		<?php $this->errorMessages($this->errors); ?>
		<p class="active"><?php echo $this->translate('Ya estoy registrado. '); ?>
			<a href="<?php echo $this->url(array('controller' => 'account', 'action' => 'login'), 'accountRoute'); ?>" title="<?php echo $this->translate('Iniciar sesión'); ?>"><?php echo $this->translate('Iniciar sesión'); ?></a>
		</p>
		<?php echo $this->form_register; ?>
	</div><!-- .span5 -->
	<div class="span7">	            
	</div><!-- .span7 -->
</div><!-- .row-fluid -->	