<?php
	$this->headTitle()->prepend($this->translate('Editar Perfil :: ')); 
?>
<?php echo $this->partial('partials/_admin_menu.phtml'); ?>
<div class="row-fluid">
	<div class="span5">
		<?php $this->successMessages($this->messages); ?>	
		<?php $this->errorMessages($this->errors); ?>						
		<?php echo $this->form_profile; ?>
	</div><!-- .span5 -->
	<div class="span7">	            
	</div><!-- .span7 -->
</div><!-- .row-fluid -->