<?php
	$this->headTitle()->prepend($this->translate('Política de cookies :: ')); 
?>
<h2><?php echo $this->translate('POLÍTICA DE COOKIES:'); ?></h2>
<h3><?php echo $this->translate('Utilización de cookies'); ?></h3>
<p><?php echo $this->translate('En este sitio web, Ecómetro. Asociación para la Medición y Difusión de la Ecología en la Arquitectura utiliza cookies, no
obstante cuando el usuario visita este sitio web no queda registrado de forma automática ningún dato de carácter personal que identifique a un Usuario.'); ?></p>
<p><?php echo $this->translate('Durante la navegación el sistema recoge una serie de información impersonal para facilitar la navegación del Usuario y mejorar la gestión del sitio web, a través de dispositivos denominados “cookies”. Estos datos son p.ej.: tipo de navegador, sistema operativo, dirección IP, ...'); ?></p>
<p><?php echo $this->translate('El sistema también mantiene identificado de forma anónima al usuario para facilitar la navegación en el sitio web. Esta
identificación se mantiene durante la sesión hasta que el usuario cierre el navegador.'); ?></p>
<p><?php echo $this->translate('El Usuario puede libremente decidir acerca de la implantación o no en su disco duro de nuestras cookies así como su
eliminación, siguiendo el procedimiento establecido en la sección de ayuda de su navegador. El Usuario puede también
configurar su navegador para aceptar o rechazar por defecto todas las cookies o para recibir un aviso de la recepción de
cada cookie y decidir en ese momento su implantación o no en su disco duro.'); ?></p>
<p><?php echo $this->translate('La cookie que utilizamos para obtener y analizar la información de la navegación es:'); ?></p>
<strong><?php echo $this->translate('Google Analytics:'); ?></strong>
<p><?php echo $this->translate('_utma, _utmb, _utmc, _utmz'); ?>/p>
<ul style="list-style-type:disc; margin: 20px;">
	<li><a href="http://www.google.com/analytics" target="_blank" title="http://www.google.com/analytics">http://www.google.com/analytics</a> y <a href="http://www.google.es/intl/es/analytics/privacyoverview.html" target="_blank" title="http://www.google.es/intl/es/analytics/privacyoverview.html">http://www.google.es/intl/es/analytics/privacyoverview.html</a></li>
	<li><?php echo $this->translate('Esta aplicación ha sido desarrollada por Google, que nos presta el servicio de análisis de la audiencia de
nuestra página. Esta empresa puede utilizar estos datos para mejorar sus propios servicios y para ofrecer
servicios a otras empresas. Puedes conocer esos otros usos desde los enlaces indicados.'); ?></li>
	<li><?php echo $this->translate('Esta herramienta no obtiene datos de los nombres o apellidos de los usuarios ni de la dirección postal desde
donde se conectan. La información que obtiene está relacionada por ejemplo con el número de páginas visitas,
el idioma, red social en la que se publican nuestras noticias, la ciudad a la que está asignada la dirección IP
desde la que acceden los usuarios, el número de usuarios que nos visitan, la frecuencia y reincidencia de las
visitas, el tiempo de visita, el navegador que usan, el operador o tipo de terminal desde el que se realiza la
visita.'); ?></li>
	<li><?php echo $this->translate('Esta información la utilizamos para mejorar nuestra página, detectar nuevas necesidades y valorar las mejoras a introducir con la finalidad de prestar un mejor servicio a los usuarios que nos visitan.'); ?></li>	
</ul>
<p><strong><?php echo $this->translate('Para permitir, conocer, bloquear o eliminar las cookies instaladas en tu equipo puedes hacerlo mediante la
configuración de las opciones del navegador instalado en su ordenador.'); ?></strong></p>
<p><?php echo $this->translate('Por ejemplo puedes encontrar información sobre cómo hacerlo en el caso que uses como navegador:'); ?></p>
<ul style="list-style-type:disc; margin: 20px;">
	<li><strong>Firefox</strong> aquí: <a href="http://support.mozilla.org/es/products/firefox/cookies" target="_blank" title="Firefox">http://support.mozilla.org/es/products/firefox/cookies</a></li>
	<li><strong>Chrome</strong> aquí: <a href="http://support.google.com/chrome/bin/answer.py?hl=es&answer=95647" target="_blank" title="Chrome">http://support.google.com/chrome/bin/answer.py?hl=es&answer=95647</a></li>
	<li><strong>Explorer</strong> aquí: <a href="http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9
" target="_blank" title="Explorer">http://windows.microsoft.com/es-es/windows7/how-to-manage-cookies-in-internet-explorer-9</a></li>
	<li><strong>Safari</strong> aquí: <a href="http://support.apple.com/kb/ph5042" target="_blank" title="Safari">http://support.apple.com/kb/ph5042</a></li>
	<li><strong>Opera</strong> aquí: <a href="http://help.opera.com/Windows/11.50/es-ES/cookies.html" target="_blank" title="Opera">http://help.opera.com/Windows/11.50/es-ES/cookies.html</a></li>
</ul>