<p class="control-label"><strong><?php echo $this->translate('Condiciones legales'); ?></strong></p>
<div class="controls">
	<div class="input-xlarge" style="height: 200px; padding: 5px; overflow-y: scroll;">
		<p><strong><?php echo $this->translate('CLAÚSULA INFORMATIVA DE REGISTRO DE NUEVO USUARIO:'); ?></strong></p>
		<p><?php echo $this->translate('De acuerdo con lo dispuesto en el artículo 5 de la Ley Orgánica 15/1999, de 13 de diciembre, de protección de datos de carácter personal (LOPD) el solicitante queda informado de:'); ?></p>
		<p><?php echo $this->translate('1.- Sus datos personales se incorporarán a los ficheros de datos personales cuya titularidad ostenta ECÓMETRO. ASOCIACIÓN PARA LA MEDICIÓN Y DIFUSIÓN DE LA ECOLOGÍA EN LA ARQUITECTURA, con domicilio social en la calle Villanueva 35 de Madrid.'); ?></p>
		<p>
			<?php echo $this->translate('2.- Las finalidades de los tratamientos de los datos personales serán:'); ?>
			<ul style="list-style-type:disc; margin: 20px;">
				<li><?php echo $this->translate('El examen de su solicitud como asociado y estimar su ingreso en la Asociación.'); ?></li>
				<li><?php echo $this->translate('Gestión de las actividades de la Asociación y de sus órganos de representación.'); ?></li>
				<li><?php echo $this->translate('Gestión de las relaciones jurídico-económicas entre la Asociación y sus asociados.'); ?></li>
				<li><?php echo $this->translate('Gestión y organización de las actividades de todo tipo que se desarrollen para el cumplimiento de los fines de la Asociación.'); ?></li>
				<li><?php echo $this->translate('La ejecución de los Estatutos de la Asociación, que el solicitante declara conocer y aceptar.'); ?></li>
			</ul>
		</p>
		<p>
			<?php echo $this->translate('3.- Las cesiones de datos que se efectuarán serán las siguientes:'); ?>
			<ul style="list-style-type:disc; margin: 20px;">
				<li><?php echo $this->translate('A la entidad bancaria en la que la Asociación disponga de la cuenta corriente para la domiciliación del pago de la cuota de asociado.'); ?></li>
				<li><?php echo $this->translate('Las que resulten de la ejecución de los Estatutos de la Asociación que el solicitante declara conocer y aceptar.'); ?></li>
				<li><?php echo $this->translate('Las que se realicen bajo los supuestos previstos en el artículo 11 de la LOPD.'); ?></li>
			</ul>
		</p>
		<p>
			<?php echo $this->translate('4.- Ejercicio de derechos de acceso, rectificación, cancelación y oposición: los interesados podrán ejercitar estos derechos en los términos recogidos en la LOPD y normativa de desarrollo, dirigiéndose a la Secretaría de la Asociación en su domicilio (calle Veneras 9 / 28013 Madrid).'); ?>
		</p>
	</div>
</div>