<ul class="nav nav-tabs">
	<li class="active"><a href="#tab1" data-toggle="tab" title="<?php echo $this->translate('Información general'); ?>"><?php echo $this->translate('Información general'); ?></a></li>
	<li><a href="#tab2" data-toggle="tab" title="<?php echo $this->translate('Normativa'); ?>"><?php echo $this->translate('Normativa'); ?></a></li>
	<li><a href="#tab3" data-toggle="tab" title="<?php echo $this->translate('Documentación'); ?>"><?php echo $this->translate('Documentación'); ?></a></li>
	<li><a href="#tab4" data-toggle="tab" title="<?php echo $this->translate('Otras certificaciones'); ?>"><?php echo $this->translate('Otras certificaciones'); ?></a></li>
	<li><a href="#tab5" data-toggle="tab" title="<?php echo $this->translate('Debate en Foro'); ?>"><?php echo $this->translate('Debate en Foro'); ?></a></li>
</ul>