<div class="tabbable">
    <ul class="nav nav-tabs">
    	<li class="active"><a href="#tab1" data-toggle="tab"><?php echo $this->translate('Información general'); ?></a></li>
      <li><a href="#tab2" data-toggle="tab"><?php echo $this->translate('Normativa'); ?></a></li>
      <li><a href="#tab3" data-toggle="tab"><?php echo $this->translate('Documentación'); ?></a></li>
      <li><a href="#tab4" data-toggle="tab"><?php echo $this->translate('Otras certificaciones'); ?></a></li>
      <li><a href="#tab5" data-toggle="tab"><?php echo $this->translate('Debate en Foro'); ?></a></li>
    </ul>
    <div class="tab-content">
    	<div class="tab-pane active" id="tab1">
        <h3><?php echo $this->translate('Background:'); ?></h3>
			  <p><?php echo $this->translate('Para ver las referencias completas de la documentación pinche aquí.'); ?></p>
			  <h3><?php echo $this->translate('Normativa:'); ?></h3>
			  <p><?php echo $this->translate('UE. 2008. Valores límite y umbrales para la protección de la salud y la vegetación. DIRECTIVA 2008/50/CE DEL PARLAMENTO EUROPEO Y DEL CONSEJO de 21 de mayo de 2008 relativa a la calidad del aire ambiente y a una atmósfera más limpia en Europa. DIRECTIVA 2004/107/CE DEL PARLAMENTO EUROPEO Y DEL CONSEJO de 15 de diciembre de 2004 relativa al arséni- co, el cadmio, el mercurio, el níquel y los hidrocarburos aromáticos policíclicos en el aire ambiente BOE. 2011. Valores límite para diferentes contaminantes. Real Decreto 102/2011, de 28 de enero relativo a la mejora de la calidad del aire.'); ?></p>
			  <h3><?php echo $this->translate('Documentación:'); ?></h3>
			  <p><?php echo $this->translate('OMS 2005. Valores máximos fijados: PM2,5: 10 μg/m3de media anual, 25 μg/m3 de edia en 24h. PM10 20 μg/m3 media anual, 50 μg/m3 de media en 24h. O3: 100μg/m3 de media en 8h. NO2: 40 μg/m3 de media anual, 200 μg/m3 de media en1h. SO2: 20 μg/m3 de media en 24h, 500 μg/m3 de media en 10 min. http://www.who.int/phe/health_topics/outdoorair_aqg/es/index'); ?></p>
    	</div>
    	<div class="tab-pane" id="tab2">
      	<h3><?php echo $this->translate('Background:'); ?></h3>
				<p><?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacus dui, pellentesque a feugiat vel, adipiscing ac ligula. Fusce ultrices pellentesque lectus eget mattis. Donec adipiscing dolor purus, sit amet faucibus velit. Aliquam euismod elementum tortor ac porttitor. Pellentesque mauris est, gravida vitae pulvinar a, porttitor nec lorem. Sed et tellus quam. Sed condimentum lectus quis ipsum facilisis euismod consectetur ipsum pellentesque. Aliquam ac sapien ac nisl porttitor porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accumsan, arcu ac elementum consectetur, nisl neque eleifend tellus, ut cursus nunc augue vitae dolor. Sed porta scelerisque tortor, sed auctor nisi accumsan a. Suspendisse fringilla imperdiet arcu, in euismod nibh consectetur sit amet. Nulla facilisi. In hac habitasse platea dictumst. Integer orci nunc, convallis a molestie vel, egestas quis augue.'); ?></p>
    	</div>
      <div class="tab-pane" id="tab3">
      	<h3><?php echo $this->translate('Background:'); ?></h3>
				<p><?php echo $this->translate('Para ver las referencias completas de la documentación pinche aquí.'); ?></p>
				<h3><?php echo $this->translate('Normativa:'); ?></h3>
				<p><?php echo $this->translate('UE. 2008. Valores límite y umbrales para la protección de la salud y la vegetación. DIRECTIVA 2008/50/CE DEL PARLAMENTO EUROPEO Y DEL CONSEJO de 21 de mayo de 2008 relativa a la calidad del aire ambiente y a una atmósfera más limpia en Europa. DIRECTIVA 2004/107/CE DEL PARLAMENTO EUROPEO Y DEL CONSEJO de 15 de diciembre de 2004 relativa al arséni- co, el cadmio, el mercurio, el níquel y los hidrocarburos aromáticos policíclicos en el aire ambiente BOE. 2011. Valores límite para diferentes contaminantes. Real Decreto 102/2011, de 28 de enero relativo a la mejora de la calidad del aire.'); ?></p>
				<h3><?php echo $this->translate('Documentación:'); ?></h3>
			 	<p><?php echo $this->translate('OMS 2005. Valores máximos fijados: PM2,5: 10 μg/m3de media anual, 25 μg/m3 de edia en 24h. PM10 20 μg/m3 media anual, 50 μg/m3 de media en 24h. O3: 100μg/m3 de media en 8h. NO2: 40 μg/m3 de media anual, 200 μg/m3 de media en1h. SO2: 20 μg/m3 de media en 24h, 500 μg/m3 de media en 10 min. http://www.who.int/phe/health_topics/outdoorair_aqg/es/index'); ?></p>
    	</div>
      <div class="tab-pane" id="tab4">
      	<h3><?php echo $this->translate('Background:'); ?></h3>
				<p><?php echo $this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lacus dui, pellentesque a feugiat vel, adipiscing ac ligula. Fusce ultrices pellentesque lectus eget mattis. Donec adipiscing dolor purus, sit amet faucibus velit. Aliquam euismod elementum tortor ac porttitor. Pellentesque mauris est, gravida vitae pulvinar a, porttitor nec lorem. Sed et tellus quam. Sed condimentum lectus quis ipsum facilisis euismod consectetur ipsum pellentesque. Aliquam ac sapien ac nisl porttitor porta. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accumsan, arcu ac elementum consectetur, nisl neque eleifend tellus, ut cursus nunc augue vitae dolor. Sed porta scelerisque tortor, sed auctor nisi accumsan a. Suspendisse fringilla imperdiet arcu, in euismod nibh consectetur sit amet. Nulla facilisi. In hac habitasse platea dictumst. Integer orci nunc, convallis a molestie vel, egestas quis augue.'); ?></p>
    	</div>
      <div class="tab-pane" id="tab5">
      	<h3><?php echo $this->translate('Background:'); ?></h3>
				<p><?php echo $this->translate('Para ver las referencias completas de la documentación pinche aquí.'); ?></p>
				<h3><?php echo $this->translate('Normativa:'); ?></h3>
				<p><?php echo $this->translate('UE. 2008. Valores límite y umbrales para la protección de la salud y la vegetación. DIRECTIVA 2008/50/CE DEL PARLAMENTO EUROPEO Y DEL CONSEJO de 21 de mayo de 2008 relativa a la calidad del aire ambiente y a una atmósfera más limpia en Europa. DIRECTIVA 2004/107/CE DEL PARLAMENTO EUROPEO Y DEL CONSEJO de 15 de diciembre de 2004 relativa al arséni- co, el cadmio, el mercurio, el níquel y los hidrocarburos aromáticos policíclicos en el aire ambiente BOE. 2011. Valores límite para diferentes contaminantes. Real Decreto 102/2011, de 28 de enero relativo a la mejora de la calidad del aire.'); ?></p>
				<h3><?php echo $this->translate('Documentación:'); ?></h3>
			  <p><?php echo $this->translate('OMS 2005. Valores máximos fijados: PM2,5: 10 μg/m3de media anual, 25 μg/m3 de edia en 24h. PM10 20 μg/m3 media anual, 50 μg/m3 de media en 24h. O3: 100μg/m3 de media en 8h. NO2: 40 μg/m3 de media anual, 200 μg/m3 de media en1h. SO2: 20 μg/m3 de media en 24h, 500 μg/m3 de media en 10 min. http://www.who.int/phe/health_topics/outdoorair_aqg/es/index'); ?></p>
      </div>
    </div>
</div><!-- .tabbable -->