<table class="valoracion">
    <thead>
        <tr>
            <th colspan="5">&nbsp;</th>
        </tr>    
    </thead>
    <tbody>    
    <?php for($count = 0; $count < $this->nrColumnsTotal; $count++): ?>
        <?php $data = explode(':', $this->comments[$count + 1]); ?>
        <tr class="<?php echo ($this->fieldsAplicable[$count+1] == 0) ? 'valoracion-no' : '';  ?>">
            <?php if (is_array($this->vectorPoints[$count])): ?>
                <?php for($cell = 1; $cell <= 5; $cell++): ?>
                <td class="grade-<?php echo $cell; ?><?php echo ($data[0] == $cell ? ' ' . 'valoracion-selected' : ''); ?>">
                    <a class="grade-btn" data-html="true" title="" data-content="<form method='post'><a class='right-close' title='<?php echo $this->translate('Cerrar'); ?>'><img src='<?php echo $this->serverUrl() . "/skins/ecometro/img/close.png"; ?>' alt='' width='16' height='16' /></a><textarea rows='4' cols='40'><?php echo ($data[0] == $cell ? $data[1] : ''); ?></textarea><div><div class='left'>Comentarios y especificaciones para la valoración</div><div class='right'><input id='submit' class='boton red' type='submit' value='Guardar' name='submit'></input></div></div><div class='clr'></div></form>" data-placement="top" data-toggle="popover" href="#">
                        <?php echo $this->vectorPoints[$count]['v' . $cell]; ?>
                    </a>
                </td>
                <?php endfor; ?> 
            <?php else: ?>
                <td colspan="5" class="none-value"><?php echo $this->translate($this->vectorPoints[$count]); ?></td>
            <?php endif; ?>               
        </tr>        
    <?php endfor; ?>
    </tbody>
</table>