<tr>
	<td>
		<?php if($this->photo): ?>
				<img style="text-align: left;" src="<?php echo $this->serverUrl() . Zend_Registry::get('config')->paths->frontend->images . 'profiles/' . $this->photo; ?>" width="25" alt="">
		<?php else: ?>
				<img style="text-align: left;" src="<?php echo $this->serverUrl() . Zend_Registry::get('config')->paths->frontend->images . 'user-default.png'; ?>" width="25" alt=""> 
		<?php endif; ?>	
	</td>
	<td><?php echo $this->username; ?></td>
	<td><?php echo $this->lastname; ?></td>
	<td><?php echo $this->firstname; ?></td>	
	<td><?php echo $this->role; ?></td>
	<td><?php echo $this->total_projects; ?></td>
	<td><?php echo $this->public_projects; ?></td>
	<td><?php echo $this->private_projects; ?></td>
	<td class='links'>
		<a href='<?php echo $this->url(array('controller' => 'account', 'action' => 'update', 'id' => $this->id), 'accountIdRoute'); ?>' title="<?php echo $this->translate('Actualizar'); ?>"><?php echo $this->translate('Actualizar'); ?></a>
		<a href='<?php echo $this->url(array('controller' => 'account', 'action' => 'delete', 'id' => $this->id), 'accountIdRoute'); ?>' title="<?php echo $this->translate('Borrar'); ?>"><?php echo $this->translate('Borrar'); ?></a>
	</td>
</tr>