<?php
	$this->headTitle()->prepend($this->translate('Paso 2 :: Mp7 :: ')); 
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 2)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php 
				echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".');
			?>
        </p>
		<div class="mp">
            <h2><span class="big"><?php echo $this->translate('mp7'); ?></span> <?php echo $this->translate('Ambiente local. Ruido exterior. Luz.'); ?> <span><?php echo $this->translate('Conocer los niveles de exposición a ruido, luz, olores,...'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Niveles sonoros equivalentes de ruido día, tarde y noche en el área y las principales fuentes de emisión para considerar medidas de protección.'); ?></p>
		</div>
        <hr>
        <?php $this->successMessages($this->messages); ?>	 	
	    <?php $this->errorMessages($this->errors); ?>            
		<?php echo $this->form_step2_mp_7; ?>
        <hr>
            <div class="tabbable">
			    <?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			    <div class="tab-content">
			    	<div class="tab-pane active" id="tab1">
			        	<h3><?php echo $this->translate('Herramientas'); ?></h3>
						<p><?php echo $this->translate('UE. Noise observation and information service for Europe:'); ?></p>
						<p><a href="http://noise.eionet.europa.eu/viewer.html" title="http://noise.eionet.europa.eu/viewer.html" target="_blank">http://noise.eionet.europa.eu/viewer.html</a></p>
						<p><?php echo $this->translate('Madrid Ayto. Calidad del aire y contaminación acústica, estaciones de medición:'); ?></p>
						<p><a href="http://www.mambiente.munimadrid.es/svca/index.php?lang=es" title="http://www.mambiente.munimadrid.es/svca/index.php?lang=es" target="_blank">http://www.mambiente.munimadrid.es/svca/index.php?lang=es</a></p>
						<p><?php echo $this->translate('MARM. Sistema de información sobre contaminación acústica.'); ?></p>
						<p><a href="http://sicaweb.cedex.es/" title="http://sicaweb.cedex.es/" target="_blank">http://sicaweb.cedex.es/</a></p>						
					</div>
			    	<div class="tab-pane" id="tab2">			      	
						<p><?php echo $this->translate('DBHR. CTE. Protección frente a ruido procedente del exterior en función del índice de ruido día Ld (dBA). Si no existen datos oficiales se aplica Ld=60dBA para el tipo de área acústica relativo a sectores de territorio con predominio de suelo de uso residencial (10dBA menos en zonas tranquilas)'); ?></p>
			    	</div>
					<div class="tab-pane" id="tab3">
						<p><?php echo $this->translate('WHO. 1995. Guidelines for community noise. Recomendación por ejemplo de menos de 30dBA en dormitorios, o 35dBA en aulas.'); ?></p>
					</div>
					<div class="tab-pane" id="tab4">
			      		<h3><?php echo $this->translate('OTROS'); ?></h3>
						<p><?php echo $this->translate('MARM. Sistema municipal de indicadores de sostenibilidad. 2010.'); ?></p>
						<p><a href="(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf)" title="(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf)" target="_blank">(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf)</a></p>
						<p><?php echo $this->translate('Ámbito 04 Metabolismo urbano.'); ?></p>
						<p><?php echo $this->translate('Punto 20 Confort acústico. población con afectación sonora diurna inferior a 65 dB(A) / número total de habitantes. población con afectación sonora nocturna inferior a 55 dB(A) / número total de habitantes. Deseable: Ruido diurno:< 65 dB(A); >60% población  Ruido noct.:< 55 dB(A); >80% población.'); ?></p>
			    	</div>
					<div class="tab-pane" id="tab5">	
						<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>		      	
					</div>
			    </div>
			</div><!-- .tabbable -->
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step2/step2functions.js'; ?>"></script>