<?php
	$this->headTitle()->prepend($this->translate('Paso 2 :: Mp2 :: ')); 
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 2)); ?>
<div class="row-fluid">
	<div class="span12">	
		<p class="intro">
			<?php 
				echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".');
			?>
		</p>
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('mp2'); ?></span> <?php echo $this->translate('Valor del suelo. Ocupación y riesgos.'); ?> <span><?php echo $this->translate('Conocer  las características del suelo.'); ?></span></h2>
		</div>
		<div class="descripcion">
			<p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Uso previo. Indicios de contaminación. Riesgos.'); ?></p>
		</div>
		<hr>	
		<?php $this->successMessages($this->messages); ?>	 	
	    <?php $this->errorMessages($this->errors);	?>		
		<?php echo $this->form_step2_mp_2; ?>
		<hr>
		<div class="tabbable">
		    <?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
		    <div class="tab-content">
		    	<div class="tab-pane active" id="tab1">
		        	<h3><?php echo $this->translate('Herramientas'); ?></h3>
					<p><?php echo $this->translate('IDEE: Infraestructura de datos espaciales de España.'); ?></p>
					<p><a href="http://www.idee.es/" title="http://www.idee.es/" target="_blank">http://www.idee.es/</a></p>
					<p><?php echo $this->translate('IDEAGE: Infraestructura de Datos Espaciales de la Administración General del Estado'); ?></p>
					<p><a href="http://www.ideage.es" title="http://www.ideage.es" target="_blank">http://www.ideage.es</a></p>
					<p><?php echo $this->translate('SIOSE: Sistema de Información sobre Ocupación del Suelo de España'); ?></p>
					<p><?php echo $this->translate('M Fomento. Infraestructura de datos espaciales, CORINE ocupación del suelo:'); ?></p>
					<p><a href="http://www.idee.es/clientesIGN/analisis_territorial/index.html" title="http://www.idee.es/clientesIGN/analisis_territorial/index.html" target="_blank">http://www.idee.es/clientesIGN/analisis_territorial/index.html</a></p>
					<p><?php echo $this->translate('MFOM: Sistema de información urbana SIU.'); ?></p>
					<p><a href="http://siu.vivienda.es/siu/PortalSiu.html" title="http://siu.vivienda.es/siu/PortalSiu.html" target="_blank">http://siu.vivienda.es/siu/PortalSiu.html</a></p>
		    	</div>
		    	<div class="tab-pane" id="tab2">
		      	
		    	</div>
				<div class="tab-pane" id="tab3">
					<h3><?php echo $this->translate('MARM. BPIA. Banco público de indicadores ambientales.'); ?></h3>
					<p><?php echo $this->translate('DESASTRES NATURALES Y TECNOLÓGICOS: Accidentes industriales en los que intervienen sustancias peligrosas. Accidentes por carretera y ferrocarril con posibles daños ambientales. Accidentes marítimos con vertido de hidrocarburos. Incendios forestales. Periodos de sequía. Víctimas mortales debidas a desastres naturales'); ?></p>
				</div>
				<div class="tab-pane" id="tab4">
					<h3><?php echo $this->translate('BNB'); ?></h3>
					<p><?php echo $this->translate('6 LOCATION PROFILE. 6.1 Location profile.  6.1.1 Risks at the micro-site.'); ?></p>
		    	</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>		      	
				</div>
		    </div>
		</div><!-- .tabbable -->
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step2/step2functions.js'; ?>"></script>