<?php
	$this->headTitle()->prepend($this->translate('Paso 2 :: Mp3 :: ')); 
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 2)); ?>
<div class="row-fluid">
	<div class="span12">		
		<p class="intro">			
			<?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('mp3'); ?></span>
				<?php echo $this->translate('Valor del suelo. Permeabilidad y gestión de escorrentías.'); ?> <span><?php echo $this->translate('Conocer la capacidad de retención de agua del terreno, y las posibles cargas de agua en temporadas lluviosas.'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Conocer la capacidad de retención de agua del terreno, y las posibles cargas de agua en temporadas lluviosas.'); ?></p>
		</div>
        <hr>
        <?php $this->successMessages($this->messages); ?>	 	
	    <?php $this->errorMessages($this->errors);	?>		
		<?php echo $this->form_step2_mp_3; ?>
        <hr>
            <div class="tabbable">
			    <?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			    <div class="tab-content">
			    	<div class="tab-pane active" id="tab1">
			        <h3><?php echo $this->translate('Herramientas'); ?></h3>
						<p><?php echo $this->translate('MARM. Sistema integrado de información del agua. SIA.'); ?></p>
						<p><a href="http://servicios2.marm.es/sia/consultas/servlet/consultas.GlobalFilter?tipo=masiva&sid=generate" title="http://servicios2.marm.es/sia/consultas/servlet/consultas.GlobalFilter?tipo=masiva&sid=generate" target="_blank">http://servicios2.marm.es/sia/consultas/servlet/consultas.GlobalFilter?tipo=masiva&sid=generate</a></p>
						<p><?php echo $this->translate('IGME. Mapa de permeabilidad (Muy alta, Alta, Media, Baja y Muy baja).'); ?></p>
						<p><a href="http://www.igme.es/infoigme/visor/" title="http://www.igme.es/infoigme/visor/" target="_blank">http://www.igme.es/infoigme/visor/</a></p>
					</div>
			    	<div class="tab-pane" id="tab2">			      	
			    	</div>
					<div class="tab-pane" id="tab3">
					</div>
					<div class="tab-pane" id="tab4">
			      		<h3><?php echo $this->translate('OTROS'); ?></h3>
						<p><?php echo $this->translate('MARM. Sistema de indicadores del agua.'); ?></p>
						<p><a href="http://servicios2.marm.es/sia/indicadores/mapa_indic.jsp" title="http://servicios2.marm.es/sia/indicadores/mapa_indic.jsp" target="_blank">http://servicios2.marm.es/sia/indicadores/mapa_indic.jsp</a></p>
			    	</div>
					<div class="tab-pane" id="tab5">	
						<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>		      	
					</div>
			    </div>
			</div><!-- .tabbable -->
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step2/step2functions.js'; ?>"></script>