<?php
	$this->headTitle()->prepend($this->translate('Paso 2 :: Mp14 :: ')); 
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 2)); ?>
<div class="row-fluid">
	<div class="span12">	
		<p class="intro">
			<?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('mp14'); ?></span> <?php echo $this->translate('Redes locales. Gestión de residuos en uso. '); ?> <span><?php echo $this->translate('Conocer las redes de residuos para garantizar una gestión sostenible de los residuos domésticos.'); ?></span></h2>
		</div>
		<div class="descripcion">
			<p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Conocer la ubicación más cercana de contenedores para reciclaje doméstico. Distancia a contenedores de papel, envases y vidrio. Distancia a un “punto limpio”. Distancia a un punto para compostaje'); ?></p>
		</div>
		<hr>            
        <?php $this->successMessages($this->messages); ?>	 	
	    <?php $this->errorMessages($this->errors); ?>    
		<?php echo $this->form_step2_mp_14; ?>
		<hr>
		<div class="tabbable">
			    <?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			    <div class="tab-content">
			    	<div class="tab-pane active" id="tab1">	
			    		<h3><?php echo $this->translate('Herramientas'); ?></h3>
			    		<p><?php echo $this->translate('OCU.Info de puntos limpios:'); ?> </p>
			    		<p><a href="http://www.ocu.org/puntos-limpios/" title="http://www.ocu.org/puntos-limpios/" target="_blank">http://www.ocu.org/puntos-limpios/</a></p>
			    		<p><?php echo $this->translate('Fundación Ecolec. Mapa de puntos limpios:'); ?></p>
			    		<p><a href="http://www.ecolec.es/puntoslimpios.asp" title="http://www.ecolec.es/puntoslimpios.asp" target="_blank">http://www.ecolec.es/puntoslimpios.asp</a></p>
					</div>
			    	<div class="tab-pane" id="tab2">			    		
			    	</div>
					<div class="tab-pane" id="tab3">
						<h3><?php echo $this->translate('MARM. BPIA. Banco público de indicadores ambientales.'); ?></h3>
						<p><?php echo $this->translate('RESIDUOS:'); ?></p>
						<p><?php echo $this->translate('Generación de residuos urbanos.'); ?></p>
						<p><a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Generacion_tcm7-164684.pdf" title="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Generacion_tcm7-164684.pdf" target="_blank">(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Generacion_tcm7-164684.pdf)</a></p>
						<p><?php echo $this->translate('Gestión de residuos urbanos: vertido e incineración. Producción y destino de lodos de instalaciones de depuración.'); ?></p>
						<p><a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Gesti%C3%B3n_tcm7-164723.pdf" title="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Gesti%C3%B3n_tcm7-164723.pdf" target="_blank">(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Gesti%C3%B3n_tcm7-164723.pdf)</a></p>
						<p><?php echo $this->translate('Reciclaje y valorización de residuos de envases.'); ?></p>
						<p><a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Reciclado_envases_tcm7-164683.pdf" title="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Reciclado_envases_tcm7-164683.pdf" target="_blank">(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Reciclado_envases_tcm7-164683.pdf)</a></p>
						<p><?php echo $this->translate('Reciclaje de papel-cartón.'); ?></p>
						<p><a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Reciclaje_papel_tcm7-164686.pdf" title="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Reciclaje_papel_tcm7-164686.pdf" target="_blank">(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/informacion-ambiental-indicadores-ambientales/BPIA_2012_Ficha_web_Residuos-Reciclaje_papel_tcm7-164686.pdf)</a></p>
					</div>
					<div class="tab-pane" id="tab4">	
						<h3><?php echo $this->translate('OTROS'); ?></h3>	
						<p><?php echo $this->translate('MARM. Sistema municipal de indicadores de sostenibilidad. 2010.'); ?></p>	
						<p><a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf" title="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf" target="_blank">(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf)</a></p>
						<p><?php echo $this->translate('Ámbito 04. Metabolismo urbano.'); ?></p>
						<p><?php echo $this->translate('Punto 16 Generación de residuos sólidos urbanos: tendencia deseable < 1,2-1,4 kg/hab y día.'); ?></p>			
						<p><?php echo $this->translate('Punto 17 Recogida selectiva neta de residuos: Tendencia deseable Materia orgánica>55%; Papel y cartón: >75%; Vidrio: >75%; Envases: >50%; Voluminosos: >50%; Textil: >50%; peligrosos: >45%.'); ?></p>
					</div>
					<div class="tab-pane" id="tab5">	
						<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>		      	
					</div>
			    </div>
			</div><!-- .tabbable -->
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step2/step2functions.js'; ?>"></script>