<?php
	$this->headTitle()->prepend($this->translate('Paso 2 :: Mp12 :: ')); 
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 2)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
			<?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('mp12'); ?></span> <?php echo $this->translate('Redes locales. Agua. '); ?> <span><?php echo $this->translate('Conocer las posibilidades de conectividad de aguas.'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Conocer si existe una red de distribución de agua separativa, agua no potable para riego, inodoros u otros usos. Conocer la red de saneamiento. Conexión al sistema de saneamiento y existencia de una red separada para aguas de lluvia, grises o negras. Detectar si existe un sistema local de depuración de agua.'); ?></p>
		</div>
		<hr>            
        <?php $this->successMessages($this->messages); ?>	 	
	    <?php $this->errorMessages($this->errors); ?>
		<?php echo $this->form_step2_mp_12; ?>
        <hr>
            <div class="tabbable">
			    <?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			    <div class="tab-content">
			    	<div class="tab-pane active" id="tab1">	
			    		<h3><?php echo $this->translate('Herramientas'); ?></h3>
			    		<p><?php echo $this->translate('Puntos de vertido de aglomeraciones urbanas.'); ?></p>
			    		<p><?php echo $this->translate('SIA: Reutilización, estaciones regeneradoras de aguas residuales.'); ?></p>
			    		<p><a href="http://servicios2.marm.es/sia/consultas/servlet/consultas.GlobalFilter?tipo=masiva&sid=generate" title="http://servicios2.marm.es/sia/consultas/servlet/consultas.GlobalFilter?tipo=masiva&sid=generate" target="_blank">http://servicios2.marm.es/sia/consultas/servlet/consultas.GlobalFilter?tipo=masiva&sid=generate</a></p>
			    		<p><?php echo $this->translate('MARM. Sistema integrado de información del agua.'); ?></p>
			    		<p><a href="http://servicios2.marm.es/sia/visualizacion/lda/" title="http://servicios2.marm.es/sia/visualizacion/lda/" target="_blank">http://servicios2.marm.es/sia/visualizacion/lda/</a></p>
					</div>
			    	<div class="tab-pane" id="tab2">			    		
			    	</div>
					<div class="tab-pane" id="tab3">						
					</div>
					<div class="tab-pane" id="tab4">
			      		<h3><?php echo $this->translate('OTROS'); ?></h3>
						<p><?php echo $this->translate('MARM. Sistema municipal de indicadores de sostenibilidad. 2010.'); ?></p>	
						<p><a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf)" title="(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf" target="_blank">(http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf)</a></p>	
						<p><?php echo $this->translate('Ámbito 04. Metabolismo urbano.'); ?></p>				
						<p><?php echo $this->translate('Punto 12 Depuración de las aguas residuales urbanas. Volumen de agua residual tratada en algún sistema de saneamiento/población total del municipio)/365 días'); ?></p>
						<p><?php echo $this->translate('Ámbito 04 Metabolismo urbano.'); ?></p>					
						<p><?php echo $this->translate('Punto 13 Reutilización de las aguas residuales depuradas. volumen de agua depurada utilizada/volumen de agua depurada.'); ?></p>					
					</div>
					<div class="tab-pane" id="tab5">	
						<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>		      	
					</div>
			    </div>
			</div><!-- .tabbable -->
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step2/step2functions.js'; ?>"></script>