<?php
	$this->headTitle()->prepend($this->translate('Paso 2 :: Mp11 :: ')); 
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 2)); ?>
<div class="row-fluid">
	<div class="span12">		
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>
		<div class="mp">
            <h2><span class="big"><?php echo $this->translate('mp11'); ?></span> <?php echo $this->translate('Redes locales. Energía. '); ?> <span><?php echo $this->translate('Conocer las posibilidades de conectividad energética.'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Conocer si existe la posibilidad de suministrar energía renovable a la red eléctrica. Conocer las redes de suministro y evacuación locales y las posibilidades de conexión, por ejemplo si existe  una red de distribución local para calefacción.'); ?>
			</p>
		</div>
		<hr>            
		<?php $this->successMessages($this->messages); ?>	 	
		<?php $this->errorMessages($this->errors); ?>
		<?php echo $this->form_step2_mp_11; ?>
		<hr>
            <div class="tabbable">
			    <?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			    <div class="tab-content">
			    	<div class="tab-pane active" id="tab1">	
			    		<h3><?php echo $this->translate('Herramientas'); ?></h3>
			    		<p><?php echo $this->translate('Red eléctrica:'); ?></p>
			    		<p><a href="www.ree.es" title="www.ree.es" target="_blank">www.ree.es</a></p>
					</div>
			    	<div class="tab-pane" id="tab2">	
			    		<p><?php echo $this->translate('Andalucía:'); ?></p>
			    		<p><a href="http://www.agenciaandaluzadelaenergia.es/administracion/cartografia-energetica" title="http://www.agenciaandaluzadelaenergia.es/administracion/cartografia-energetica" target="_blank">http://www.agenciaandaluzadelaenergia.es/administracion/cartografia-energetica</a></p>
			    	</div>
					<div class="tab-pane" id="tab3">						
					</div>
					<div class="tab-pane" id="tab4">
			      		<h3><?php echo $this->translate('BNB'); ?></h3>
						<p><?php echo $this->translate('6 LOCATION PROFILE. 6.1 Location profile.   6.1.6 Supply lines/site development'); ?></p>						
					</div>
					<div class="tab-pane" id="tab5">	
						<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>		      	
					</div>
			    </div>
			</div><!-- .tabbable -->
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step2/step2functions.js'; ?>"></script>