<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: A2 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'ga2'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'ga2'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('a2'); ?></span> <?php echo $this->translate('Control del agua de suministro.'); ?> <span><?php echo $this->translate('(Calidad del agua).'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('CTE DB-HS. Salubridad. HS 4: Suministro de agua.');
		?></p>
			<p><?php echo $this->translate('Real Decreto 140/2003, por el que se establecen los criterios sanitarios de la calidad del agua de consumo humano.'); ?></p>
		</div>                    
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_ga_2; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">			    	
			    </div>
			    <div class="tab-pane" id="tab2">			    	
			    </div>
			    <div class="tab-pane" id="tab3">
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Wat 4 Sanitary supply shut-off. No aplicable.'); ?></p>					
					<h3><?php echo $this->translate('CASBEE'); ?></h3>
					<p><?php echo $this->translate('LR3 Off-site environment.'); ?>
						<ul>
							<li><?php echo $this->translate('2.3 Load on local infrastructure.'); ?>
								<?php echo $this->translate('2.3.2 Sewage load suppression. Se cumplen los estándares de calidad de descarga de agua (temperatura, pH, aceites, elementos químicos, ...)'); ?>
							</li>
						</ul>
					</p>					
					<h3><?php echo $this->translate('HQE'); ?></h3>
					<p><?php echo $this->translate('F4 : SANTE. Cible 14 : Qualité sanitaire de l’eau'); ?>						
					</p>
					<h3><?php echo $this->translate('OTROS'); ?></h3>
					<p><?php echo $this->translate('MARM. Sistema municipal de indicadores de sostenibilidad. 2010.'); ?></p>
					<p><?php echo $this->translate('4 Metabolismo urbano. '); ?></p>
					<p><?php echo $this->translate('13 Reutilización de las aguas residuales depuradas.'); ?></p>
					<p><?php echo $this->translate('Volumen de agua depurada utilizada/volumen de agua depurada.'); ?></p>
					<p><?php echo $this->translate('Enlace al documento:'); ?></p>
					<a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf" title="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf" target="_blank">http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf</a>
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>