<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: M3 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'bc3'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'bc3'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">		
		<p class="intro">
            <?php 
				echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".');
			?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('m3'); ?></span> <?php echo $this->translate('Recursos de la cuna a la puerta.'); ?> <span><?php echo $this->translate('Transporte a obra.'); ?></span></h2>
		</div>
        <div class="descripcion">
			<p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Conocer la procedencia de los materiales de construcción para poder tener en cuenta los impactos ambientales del transporte al lugar, en el análisis de ciclo de vida. Depende de:  la cantidad de material, la distancia de transporte y el tipo de vehículo utilizado para el transporte.');?>
			</p>
		</div>                      
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_bc_3; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">					
					<h3><?php echo $this->translate('Herramientas'); ?></h3>
					<p><?php echo $this->translate('Cumplimentar la tabla de inventario de ACV de materiales'); ?></p>
					<p><?php echo $this->translate('También disponible en www.ecometro.es'); ?></p>
			    </div>
			    <div class="tab-pane" id="tab2">						
			    </div>
			    <div class="tab-pane" id="tab3">
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Wst 2. Recycled aggregates. 25% (peso o vol) de áridos reciclados o secundarios.'); ?></p>
					<h3><?php echo $this->translate('LEED'); ?></h3>
					<p><?php echo $this->translate('MR C5. Regional materials. Del 10% al 20% (coste) de materiales o productos extraídos, cosechados, recuperados y procesados a menos de 800 Km de la parcela. Para materiales o componentes compuestos con una parte que no cumpla esta distancia, calcular la contribución como porcentaje (peso).'); ?></p>		
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>