<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: R6 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 're6'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 're6'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('r6'); ?></span> <?php echo $this->translate('Clima local y efecto isla de calor.'); ?> <span></span></h2>
		</div>
        <div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>			
		</div>            
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_re_6; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
		<div class="tab-content">
			<div class="tab-pane active" id="tab1">
			</div>
			<div class="tab-pane" id="tab2">
			</div>
			<div class="tab-pane" id="tab3">			      		
			</div>
			<div class="tab-pane" id="tab4">
				<h3><?php echo $this->translate('LEED'); ?></h3>
				<p><?php echo $this->translate('SS C 7.1 Heat island effect - non roof.'); ?></p>
				<p><?php echo $this->translate('Utilizar estrategias de sombreamiento (arbolado, placas solares, ...), aumento de la reflectancia, y pavimentos permeables para el 50% del "hardscape" o al menos el 50% de la superficie de aparcamiento cubierta con estas estrategias.'); ?></p>
				<p><?php echo $this->translate('SS C 7.2 Heat island effect - roof.'); ?></p>
				<p><?php echo $this->translate('Reflectancia para al menos el 75% de los materiales de cubierta de: 78 para cubiertas planas (>15%) y 29 para inclinadas.'); ?></p>
				<h3><?php echo $this->translate('CASBEE'); ?></h3>
				<p><?php echo $this->translate('LR3 Off-site environment.'); ?></p>
				<p><?php echo $this->translate('2.2 Heat island effect.'); ?></p>
				<p><?php echo $this->translate('Toma de datos previa a la actuación, facilitar el flujo de aire, materiales de cobertura de suelo, cubiertas y paredes (evaporación, reflectancia), emisiones de calor de equipos (cargas térmicas por pérdidas de calor, y unidades exteriores de aire acondicionado) y confirmación de la efectividad de la actuación.'); ?></p>
				<p><?php echo $this->translate('3.Consideration of surrounding environment.'); ?></p>
				<p><?php echo $this->translate('3.2 Wind damage and daylight obstruction.'); ?></p>
				<p><?php echo $this->translate('3.2.1 Restriction of wind damage.  Restricción de los daños por viento: Estudio preliminar. Plan de prevención y medidas de control de peligrosidad.'); ?>	
				</p>
				<p><?php echo $this->translate('3.2.2 Sand and dust. Prevenir la dispersión de polvo (solo para colegios)'); ?>
				</p>
				<p><?php echo $this->translate('3.2.3 Restriction of daylight obstruction. Evitar la obstrucción solar (por encima de la regulación).'); ?>
				</p>						
			</div>
			<div class="tab-pane" id="tab5">
				<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>
			</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>