<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: R11 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 're11'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 're11'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">		
		<p class="intro">
            <?php 
				echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".');
			?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('r11'); ?></span> <?php echo $this->translate('Espacio para reciclar basuras y compostaje.'); ?> <span></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('En las viviendas.'); ?></p>
		</div>            
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_re_11; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
	<div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
		<div class="tab-content">
			<div class="tab-pane active" id="tab1">
			</div>
			<div class="tab-pane" id="tab2">
				<p><?php echo $this->translate('CTE DB-HS Salubridad.'); ?>
					<ul>
						<li><?php echo $this->translate('HS 2: Recogida y evacuación de residuos'); ?></li>
					</ul>
				</p>
			</div>
			<div class="tab-pane" id="tab3">			      		
			</div>
			<div class="tab-pane" id="tab4">
				<h3><?php echo $this->translate('BREEAM'); ?></h3>
				<p><?php echo $this->translate('Wst 3. Recyclable waste storage.'); ?></p>
				<p><?php echo $this->translate('Espacio para tres contenedores separativos en el interior, con requisitos según el tipo de edificio, y espacio exterior accesible, señalizado y con capacidad según tipo de edificio.'); ?>
				</p>
				<p><?php echo $this->translate('Wst 4. Compactor/baler. No aplicable para residencial.'); ?>					
				</p>
				<p>
					<?php echo $this->translate('Wst 5. Composting. Contenedor para compostaje con capacidad suficiente y acceso a agua para limpieza o contenedor específico para recogida selectiva. Y folleto de información e instrucciones para cada usuario.'); ?>
				</p>
				<h3><?php echo $this->translate('CASBEE'); ?></h3>
				<p><?php echo $this->translate('LR3 Off-site environment.'); ?>
					<ul>
						<li><?php echo $this->translate('2.3.4 Waste treatment loads.'); ?></li>
						<li><?php echo $this->translate('Estimar el tipo y cantidad de resIduo diario/ Espacio interior y exterior de almacenaje separativo/ contenedores para almacenamiento/ separación de residuos valiosos/ sistemas de reducción de residuos, compactación (latas,...) y compostaje (orgánico).'); ?></li>						
					</ul>
				</p>
				<h3><?php echo $this->translate('OTROS'); ?></h3>
				<p><?php echo $this->translate('MARM. Sistema municipal de indicadores de sostenibilidad. 2010.'); ?></p>
				<p><?php echo $this->translate('4 Metabolismo urbano. 16  Generación de residuos sólidos urbanos.'); ?>
					<ul>
						<li><?php echo $this->translate('T residuos generadas por año. Kg de residuos urbanos generados y retirados por los servicios de recogida municipales / número de habitantes) / 365 días. Deseable: < 1,2-1,4 kg/hab y día.'); ?></li>
					</ul>
				</p>
				<p><?php echo $this->translate('4 Metabolismo urbano.17 Recogida selectiva neta de residuos.'); ?>
					<ul>
						<li><?php echo $this->translate('T de fracciones capturadas (brutas) en los sistemas de recogida selectiva – T impropios en los sistemas de recogida) / t totales de residuos generados por año. (t de la fracción capturada (brutas) en los sistemas de recogida selectiva – T impropios de la fracción) / T totales de residuos generados de la fracción por año. Deseable: Materia orgánica>55%; Papel y cartón: >75%; Vidrio: >75%; Envases: >50%; Voluminosos: >50%; Textil: >50%; peligrosos: >45%'); ?></li>						
					</ul>
				</p>				
				<p><?php echo $this->translate('Enlace al documento:'); ?></p>
				<p><a href="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf" title="http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf" target="_blank"><?php echo $this->translate('http://www.magrama.gob.es/es/calidad-y-evaluacion-ambiental/temas/medio-ambiente-urbano/SISTEMA_MUNICIPAL_INDICADORES_SOSTENIBILIDAD_tcm7-177732.pdf'); ?></a></p>				
			</div>
			<div class="tab-pane" id="tab5">
				<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>
			</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>