<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: D2 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'bl2'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'bl2'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('d2'); ?></span> <?php echo $this->translate('Calidad de la iluminación, acceso solar, vistas, ruido.'); ?> <span></span></h2>
		</div>
		<div class="descripcion">
			<p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>			
		</div>            
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_bl_2; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			 <?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
	<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
		<div class="tab-content">
			    <div class="tab-pane active" id="tab1">			    
			    </div>
			    <div class="tab-pane" id="tab2">
			    	<p><?php echo $this->translate('CTE DB-HR Protección frente al ruido.'); ?></p>
			    	<p><?php echo $this->translate('DBHR. CTE. Protección frente a ruido procedente del exterior en función del índice de ruido día Ld (dBA). Si no existen datos oficiales se aplica Ld=60 dBA para el tipo de área acústica relativo a sectores de territorio con predominio de suelo de uso residencial (10 dBA menos, en zonas tranquilas).'); ?></p>
			    </div>
			    <div class="tab-pane" id="tab3">
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('HADES'); ?></h3>
					<p><?php echo $this->translate('AI2. Iluminación natural'); ?></p>
					<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Hea 1.  Daylighting. '); ?>
					</p>
					<p><?php echo $this->translate('Para edificios de viviendas mínimos de factor luz día para el 80% de la superficie como mínimo. Para otros, factor luz día y/o línea de vistas y geometría de la habitación.'); ?></p>
					<p><?php echo $this->translate('Hea 2. View out.'); ?>
					</p>
					<p><?php echo $this->translate('Superficie y localización de ventanas al exterior según estancias con vistas al exterior adecuadas (en estancias relevantes, posición sentada, vistas al paisaje o patios con una profundidad mayor de 10m)'); ?></p>					
					<p><?php echo $this->translate('Hea 3. Glare control.'); ?></p>
					<p><?php echo $this->translate('Sistemas de sombreamiento controlados por el usuario para ventanas, puertas acristaladas y demás.'); ?></p>
					<p><?php echo $this->translate('Hea 4. High frequency lighting.'); ?></p>
					<p><?php echo $this->translate('Fluorescentes con balastos de alta frecuencia.'); ?></p>
					<p><?php echo $this->translate('Hea 5.  Internal and external lighting levels.'); ?></p>
					<p><?php echo $this->translate('Niveles de iluminancia interior e iluminación exterior según CIBSE.'); ?></p>
					<p><?php echo $this->translate('Hea 6. Lighting zones and controls. No aplicable para residencial.'); ?></p>
					<p><?php echo $this->translate('Hea 13 Acoustic performance. No aplicable para residencial.'); ?></p>
					<p><?php echo $this->translate('Hea 21 Sound insulation. Valoración por puntos según la atenuación del ruido aéreo y de impacto con los vecinos por encima de la regulación.'); ?></p>
					<h3><?php echo $this->translate('LEED'); ?></h3>
					<p><?php echo $this->translate('IEQ 6.1 Controllability of systems-lighting. Control de la iluminación para el 90% de los ocupantes y espacio compartido.'); ?>
					<p><?php echo $this->translate('IEQ 8.1 Daylight and views - daylight. Demostrar la calidad de iluminación natural (luminancia) mediante simulación, prescripción, medición, o combinado.'); ?></p>
					<p><?php echo $this->translate('IEQ 8.2 Daylight and views - views. Línea visual.'); ?></p>
					<h3><?php echo $this->translate('CASBEE'); ?></h3>
					<p><?php echo $this->translate('Q1 Indoor environment.'); ?></p>
					<p><?php echo $this->translate('3 Lighting and illumination.'); ?></p>
					<p><?php echo $this->translate('3.1 Daylighting'); ?>
						<ul>
							<li><?php echo $this->translate('3.1.1 Daylight factor. Factor luz día de 1% hasta 2,5% en zonas comunes, y de 0,5% a 2% en viviendas.') ?></li>
							<li><?php echo $this->translate('3.1.2 Openings by orientation. Ventanas a sur y este.'); ?></li>
							<li><?php echo $this->translate('3.1.3 Daylight devices. Utilización de sistemas de iluminación natural diferentes a ventanas.'); ?></li>
						</ul>
					</p>					
					<p><?php echo $this->translate('3.2 Anti-glare measures.'); ?>
						<ul>
							<li><?php echo $this->translate('3.2.1 Glare from light fixtures. Apantallamiento o tamización de la luminaria.'); ?></li>
							<li><?php echo $this->translate('3.2.2 Daylight control. Persianas, cortinas,.. para el control de luz natural.'); ?></li>
							<li><?php echo $this->translate('3.2.3 Reflection control. No aplicable.'); ?></li>
						</ul>
					</p>
					<p>
					<?php echo $this->translate('3.3 Illuminance level. Iluminancia mayor que 100 lx y capacidad de control individual de dispositivos.'); ?></p>
					<p><?php echo $this->translate('3.4 Lighting controllability. Zonificación y automatización.'); ?></p>
					<p><?php echo $this->translate('1 Sonic environment.'); ?></p>
					<p><?php echo $this->translate('1.1 Noise.'); ?>
						<ul>
							<li><?php echo $this->translate('1.1.1 Background noise level. Para apartamentos: ruido ambiental interior de 45 dBA a 35 dBA.'); ?></li> 
							<li><?php echo $this->translate('1.1.2 Equipment noise. Apartamentos: valoración según esfuerzos en reducción de emisión de ruido de instalaciones de abastecimiento y evacuación de agua, unidades internas y externas de acondicionamiento, y ventiladores.'); ?></li>
						</ul>	
					<?php echo $this->translate('1.2 Sound insulation.'); ?>
					<ul>
						<li><?php echo $this->translate('1.2.1 Sound insulation of openings. Nivel de aislamiento de huecos según bandas de frecuencia. 1.2.2 Sound insulation partition walls. Nivel de aislamiento de particiones por bandas de octava. 1.2.3 Sound insulation performance of floor slabs (light-weight impact source) Aislamiento a ruido de impacto ligero de forjados por bandas de octava.'); ?></li>
						<li><?php echo $this->translate('1.2.4. Sound insulation performance of floor slabs (heavy-weight impact source) Aislamiento a ruido de impacto pesado de forjados Lr según tipo de sistema constructivo.'); ?></li>
					</ul>
					<?php echo $this->translate('1.3 Sound absorption. No aplicable para apartamentos.'); ?>
					</ul>
					</p>					
					<h3><?php echo $this->translate('HQE'); ?></h3>
					<p><?php echo $this->translate('F3 CONFORT. Cible 9: Confort acoustique.'); ?></p>
					<p><?php echo $this->translate('F3 CONFORT. Cible 10: Confort visuel'); ?></p>
					<p><?php echo $this->translate('F3 CONFORT. Cible 11: Confort olfactif'); ?></p>
					<h3><?php echo $this->translate('BNB'); ?></h3>
					<p><?php echo $this->translate('3 SOCIOCULTURAL AND FUNCTIONAL QUALITY.'); ?></p>
					<p>
						<?php echo $this->translate('3.1 Health, comfort and user satisfaction.'); ?>
						<ul>
							<li><?php echo $this->translate('3.1.4 Acoustic comfort.'); ?></li>
							<li><?php echo $this->translate('3.1.5 Visual comfort.'); ?></li>
							<li><?php echo $this->translate('3.1.6 Influence of the user.'); ?></li>
						</ul>
					</p>
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>