<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: M6 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'bc6'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'bc6'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php 
				echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".');
			?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('m6'); ?></span> <?php echo $this->translate('Compuestos Orgánicos Volátiles en uso.'); ?> <span><?php echo $this->translate('Tasa de emisión.'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
            <p><?php echo $this->translate('Reducir las emisiones de compuestos orgánicos volátiles en uso.'); ?></p>
		</div>
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_bc_6; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">
			    </div>
			    <div class="tab-pane" id="tab2">			    	
			    </div>
			    <div class="tab-pane" id="tab3">			    	
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Hea 9. Volatile organic compounds.'); ?></p>
					<p><?php echo $this->translate('Utilizar productos (según listado, paneles de madera, acabados, adhesivos, pinturas,...) que han sido testados según diferentes estándares europeos para emisiones de COV.'); ?></p>
					<h3><?php echo $this->translate('LEED'); ?></h3>
					<p><?php echo $this->translate('IEQ C 4.1. Low emitting materials - Adhesives and sealants. Limitación de COV para adhesivos y sellantes.'); ?></p>
					<p><?php echo $this->translate('IEQ C 4.2. Low emitting materials - Paints and coatings. Limitación de COV para pinturas y revestimientos.'); ?></p>
					<p><?php echo $this->translate('IEQ C 4.3. Low emitting materials - Flooring systems. Suelos'); ?></p>
					<p><?php echo $this->translate('IEQ C 4.4. Low emitting materials - Composite wood and agrifiber products. Materiales compuestos-madera-fibras naturales.'); ?></p>
					<h3><?php echo $this->translate('CASBEE'); ?></h3>
					<p><?php echo $this->translate('Q1 Indoor environment.'); ?></p>
					<p><?php echo $this->translate('4 Air quality'); ?>
						<ul>
							<li><?php echo $this->translate('4.1 Source control'); ?></li>
							<li><?php echo $this->translate('4.1.1 Chemical pollutants. Según la "Building standard law" y "JIS/JAS F4 star rating".. '); ?></li>
						</ul>
					</p>					
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>