<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: M7 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'bc7'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'bc7'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('m7'); ?></span> <?php echo $this->translate('Control en obra.'); ?> <span><?php echo $this->translate('Gestión de residuos.'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>	
		</div>
		<hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_bc_7; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">
			    </div>
			    <div class="tab-pane" id="tab2">			    	
			    </div>
			    <div class="tab-pane" id="tab3">			    	
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Wst 1 Construction site waste management. '); ?></p>
					<p><?php echo $this->translate('Si no hay residuos peligrosos: puntuación según los residuos de obra (excluyendo demolición y excavación) para cada 100m2 útiles: 13-16,6m3 y 6,6-8,5t/,-12,9m3 y 4,7-6,5t/ <9,2m3 y <4,7t.'); ?></p>
					<p><?php echo $this->translate('Si existe un plan de gestión de residuos el plan contiene: la cantidad de residuos por m2, procedimientos para minimizar residuos peligrosos y no peligrosos, procedimientos para monitorizar, medir e informar, procedimientos de separación selectiva, y el nombre del responsable de llevar a cabo el plan.'); ?></p>
					<p><?php echo $this->translate('Para demoliciones y rehabilitación: realizar un estudio previo que contenga especificaciones. Un punto extra si: el 75% (peso) o el 65% (vol) se deriva, en demolición el 90% (peso) o 80% (vol) se deriva. La separación selectiva se deriva para su procesado.'); ?></p>
					<h3><?php echo $this->translate('LEED'); ?></h3>
					<p><?php echo $this->translate('MR PR 1 Storage and collection of recyclables.'); ?></p>
					<p><?php echo $this->translate('Espacio accesible para recogida y almacenamiento de residuos reciclables, al menos para papel, cartón, vidrio, plástico y metal.'); ?></p>
					<p><?php echo $this->translate('MR C2 Construction waste management.'); ?></p>
					<p><?php echo $this->translate('Reciclar o recuperar residuos de construcción y demolición no peligrosos (excluyendo tierra excavada). Plan de gestión de residuos en el que se identifiquen al menos los materiales a separar, clasificar. De 50% a 75% de residuos reciclados o recuperados.'); ?></p>
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>