<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: R8 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 're8'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 're8'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">		
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('r8'); ?></span> <?php echo $this->translate('Ambiente local.'); ?> <span><?php echo $this->translate('Otras emisiones. Luz. Ruido, vibraciones.'); ?></span></h2>
		</div>
        <div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
		</div>
        <hr>
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_re_8; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
		<div class="tab-content">
			<div class="tab-pane active" id="tab1">
			</div>
			<div class="tab-pane" id="tab2">
			</div>
			<div class="tab-pane" id="tab3">			      		
			</div>
			<div class="tab-pane" id="tab4">
				<h3><?php echo $this->translate('BREEAM'); ?></h3>
				<p><?php echo $this->translate('Ver: Calidad de la iluminación y vistas.'); ?></p>
				<p><?php echo $this->translate('Pol 7 Reduction of night time light pollution.'); ?>
					<ul>
						<li><?php echo $this->translate('Iluminación exterior y anuncios.'); ?></li>
						<li><?php echo $this->translate('Según tipo de diseño, horarios y luminosidad.'); ?></li>
					</ul>
				</p>
				<p><?php echo $this->translate('Hea 15 Outdoor space.'); ?>
					<ul>
						<li><?php echo $this->translate('Espacio exterior que: Es adecuado en tamaño/ accesible/ se sitúa en parcela, balcones o terrazas/ es privada y está protegida de ruidos, coches, ... / tiene asientos y permite a los usuarios socializar.'); ?></li>
					</ul>
				</p>
				<h3><?php echo $this->translate('LEED'); ?></h3>
				<p><?php echo $this->translate('SS C 8. Light pollution reduction.'); ?>
					<ul>
						<li>- <?php echo $this->translate('Para iluminación interior:'); ?></li>
						<li>- <?php echo $this->translate('Reducir la potencia un 50% para luminarias interiores no de emergencia que proyecten luz sobre el exterior, e instalar controles de presencia o temporizadores.'); ?></li>
						<li>- <?php echo $this->translate('Disponer sistemas de protección en huecos.'); ?></li>
						<li>- <?php echo $this->translate('Para iluminación exterior: según estándares ANSI/ASHRAE/IESNA standard 90.1-2007'); ?></li>
					</ul>
				</p>
				<h3><?php echo $this->translate('CASBEE'); ?></h3>
				<p><?php echo $this->translate('LR3 Off-site environment.'); ?></p>
				<p><?php echo $this->translate('3.Consideration of surrounding environment.'); ?></p>
				<p><?php echo $this->translate('3.1 Noise, vibration and odor.'); ?>
					<ul>
						<li><?php echo $this->translate('3.1.1 Noise.'); ?></li>
						<li><?php echo $this->translate('3.1.2 Vibration. Limitación de ruido y vibraciones según legislación para instalaciones reguladas.'); ?></li>
						<li><?php echo $this->translate('3.1.3 Odor. Índice de olor según legislación de control de olores ofensivos'); ?></li>
					</ul>
				</p>
				<p><?php echo $this->translate('3.3 Light pollution.'); ?>
					<ul>
						<li><?php echo $this->translate('3.3.1. Outdoor illumination and light that spills from interiors. Para iluminación exterior: según la guía del ministerio de medio ambiente de Japón.'); ?></li>
						<li><?php echo $this->translate('Measures for reflected solar glare from building walls. Reflejos de paredes: Reducir la reflectancia, superficies que difundan o ajustar el ángulo de reflexión.'); ?></li>
					</ul>
				</p>
				<h3><?php echo $this->translate('BNB'); ?></h3>
				<p><?php echo $this->translate('3 Sociocultural and functional quality.'); ?></p>
				<p><?php echo $this->translate('3.1 Health, comfort and user satisfaction.'); ?></p>
				<p><?php echo $this->translate('3.1.7 Building-related outdoor qualities.'); ?></p>
			</div>
			<div class="tab-pane" id="tab5">
				<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>
			</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>