<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: D5 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'bl5'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'bl5'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('d5'); ?></span> <?php echo $this->translate('Energía en uso.'); ?> <span><?php echo $this->translate('Otros.'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>			
		</div>            
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_bl_5; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">
			    </div>
			    <div class="tab-pane" id="tab2">
			    </div>
			    <div class="tab-pane" id="tab3">
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('HADES'); ?></h3>
					<p><?php echo $this->translate('EA2. Demanda de energía eléctrica en la fase de uso.'); ?></p>					
					<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Ene 4. External lighting. Eficacia y especificaciones de las luminarias exteriores, y sistema de sensores y control.'); ?>						
					</p>
					<p><?php echo $this->translate('Ene 7. Cold storage. No aplicable.'); ?></p>
					<p><?php echo $this->translate('Ene 10. Free cooling. No aplicable.'); ?>
					</p>
					<p><?php echo $this->translate('Ene 11. Energy efficient fume cupboards. No aplicable.'); ?></p>
					<p><?php echo $this->translate('Ene 12 Swimming pool ventilation and heat loss. No aplicable.'); ?></p>
					<p><?php echo $this->translate('Ene 13. Labelled lighting controls. No aplicable.'); ?></p>
					<p><?php echo $this->translate('Ene 14 BMS. No aplicable.'); ?></p>
					<p><?php echo $this->translate('Ene 15 Provision of energy efficient white goods. Según etiquetado de electrodomésticos.'); ?></p>					
					<p><?php echo $this->translate('Ene 8. Lifts. No aplicable.'); ?></p>
					<p><?php echo $this->translate('Ene 9. Escalators and travelling walkways. No aplicable.'); ?></p>
					<p><?php echo $this->translate('Ene 18 Drying space. Espacio seguro para tender. Longitud de cuerda por ocupante.'); ?></p>
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>