<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: M4 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'bc4'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'bc4'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('m4'); ?></span> <?php echo $this->translate('Recursos.'); ?> <span><?php echo $this->translate('Materiales con certificación.'); ?></span></h2>
		</div>
		<div class="descripcion">
			<p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>			
		</div>            
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_bc_4; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
            <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">					
			    </div>
			    <div class="tab-pane" id="tab2">						
			    </div>
			    <div class="tab-pane" id="tab3">
			    	<p><?php echo $this->translate('Etiqueta Ecológica Europea. EU Ecolabel.'); ?></p>
			    	<p><a href="http://www.ecolabel.eu" title="www.ecolabel.eu" target="_blank">www.ecolabel.eu</a></p>
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Mat 5 Responsible sourcing of materials - basic building elements.'); ?></p>
					<p><?php echo $this->translate('El 80% de los materiales aplicables (cerámica, resinas, hormigones, vidrios, plásticos, metales, maderas,...) para diferentes elementos (estructura, forjados, cubiertas, cerramientos,...) son de fuentes responsables.'); ?></p>
					<p><?php echo $this->translate('Mat 6. Insulation.'); ?></p>
					<p><?php echo $this->translate('Aislamientos procedentes de fuentes responsables.'); ?></p>
					<p><?php echo $this->translate('Mat 8. Responsible sourcing of materials - Finishing elements.'); ?></p>
					<p><?php echo $this->translate('El 80% de los materiales aplicables proceden de fuentes responsables.'); ?></p>
					<h3><?php echo $this->translate('LEED'); ?></h3>
					<p><?php echo $this->translate('MR C7. Certified wood. Mínimo un 50% (coste) de los materiales con base madera con certificación FSC.'); ?></p>		
					<h3><?php echo $this->translate('CASBEE'); ?></h3>
					<p><?php echo $this->translate('LR2 Resources & materials. '); ?></p>
					<p><?php echo $this->translate('2.5 Timber from sustainable forest. Utilizar del 10% al 50% (volumen) de madera procedente de bosques sostenibles, ya sea por certificación, por tipo de conífera producida en Japón, o por tipo de madera (coníferas).'); ?></p>
					<h3><?php echo $this->translate('OTROS'); ?></h3>
					<p><?php echo $this->translate('Ministerio de Fomento. Índice de contribución de la estructura a la sostenibilidad. Herramienta informática MIVES-EHE-08.'); ?></p>
					<p><a href="http://www.fomento.gob.es/MFOM/LANG_CASTELLANO/ORGANOS_COLEGIADOS/CPH/SOTENIB_ESTRUC" title="http://www.fomento.gob.es/MFOM/LANG_CASTELLANO/ORGANOS_COLEGIADOS/CPH/SOTENIB_ESTRUC" target="_blank">http://www.fomento.gob.es/MFOM/LANG_CASTELLANO/ORGANOS_COLEGIADOS/CPH/SOTENIB_ESTRUC</a></p>
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>