<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: E3 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'ge3'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'ge3'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".'); ?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('e3'); ?></span> <?php echo $this->translate('Control en uso de la energía. Información. Monitorización. Mantenimiento.'); ?> <span><?php echo $this->translate('¿Estás garantizando un uso sencillo y eficaz por parte del usuario?'); ?></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p></p>
		</div>
        <hr>
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_ge_3; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
    <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">					
			    </div>
			    <div class="tab-pane" id="tab2">						
			    </div>
			    <div class="tab-pane" id="tab3">
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Ene 2 Sub-metering of substantial energy uses. Contadores separados y accesibles para: calefacción, agua caliente, humidificación, refrigeración, ventiladores, iluminación,... .'); ?></p>
					<p><?php echo $this->translate('Ene 3 Sub-metering of high energy load and tenancy areas. No aplicable. (Ver energía en uso, iluminación exterior). '); ?></p>
					<p><?php echo $this->translate('Man 1 Commissioning. Gestión de sistemas, al menos: acondicionamiento térmico, ventilación, mantenimiento, renovables,... con especialistas designadas en fase de diseño y verificación en uso.'); ?></p>
					<p><?php echo $this->translate('Man 4 Building users guide.Guía para el usuario con información relevante y comprensible sobre la mayoría de los temas evaluados.'); ?></p>
					<h3><?php echo $this->translate('LEED'); ?></h3>
					<p><?php echo $this->translate('EA PR1. Fundamental commissioning of building energy systems. Gestión energética.'); ?></p>
					<p><?php echo $this->translate('EA C3 Enhanced commissioning. Mejoras en la gestión energética.2'); ?>
					</p>
					<p><?php echo $this->translate('EA C5 Measurement and verification. Protocolo de medida y verificación. 3'); ?>
					</p>
					<h3><?php echo $this->translate('CASBEE'); ?></h3>
					<p><?php echo $this->translate('LR1 Energy.'); ?>
					</p>
					<p><?php echo $this->translate('4 Efficient operation.'); ?></p>
					<p><?php echo $this->translate('4.1 Monitoring. No aplicable para apartamentos.');?></p>
					<p><?php echo $this->translate('LR1 Energy.'); ?></p>
					<p><?php echo $this->translate('4 Efficient operation.'); ?>
					</p>
					<p><?php echo $this->translate('4.2 Operation and management system. No aplicable para apartamentos.'); ?></p>
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>