<?php
	$this->headTitle()->prepend($this->translate('Paso 3 :: A3 :: ')); 
?>
<?php 
		$myNamespace = new Zend_Session_Namespace('myNamespace');    	
    	$myNamespace->{'data_' . $this->project_id . 'ga3'} = $this->valueOfEachField;
    	$myNamespace->{'comments_' . $this->project_id . 'ga3'} = $this->comments;
?>
<?php echo $this->partial('partials/_project_menu.phtml', array('project_id' => $this->project_id, 'step' => 3)); ?>
<div class="row-fluid">
	<div class="span12">
		<p class="intro">
            <?php 
				echo $this->translate('Ve rellenando las fichas. Recuerda que puedes desmarcar los indicadores que no procedan, pinchando sobre la "X".');
			?>
		</p>		
		<div class="mp">
			<h2><span class="big"><?php echo $this->translate('a3'); ?></span> <?php echo $this->translate('Cargas de aguas residuales (cantidad).'); ?> <span></span></h2>
		</div>
		<div class="descripcion">
            <p><strong><?php echo $this->translate('Descripción:'); ?></strong></p>
			<p><?php echo $this->translate('Controlar la carga de aguas residuales evacuadas a la red o ecosistema local.');
		?></p>
		</div>                    
        <hr>													
	</div><!-- .span12 -->
</div><!-- .row-fluid -->
<?php if($this->messages || $this->errors): ?>
	<div class="row-fluid">	
		<div class="span12">
			<?php $this->successMessages($this->messages); ?>	           
			<?php $this->errorMessages($this->errors); ?>
		</div>
	<div><!-- .row-fluid -->
<?php endif; ?>
<div class="row-fluid">
	<div class="span5 content">
		<p class="titulo"><?php echo $this->translate('Recuerda los siguientes datos:'); ?></p>
            <ul>
            <?php foreach ($this->rememberFieldsData AS $key => $value): ?>
                <li><span class="titulo"><?php echo $key; ?></span>. <?php echo $value[0]; ?> <strong><?php echo $value[1]; ?></strong> <strong><?php echo $value[2]; ?></strong></li>
            <?php endforeach; ?>
            <ul>
	</div>
	<div class="span7"></div><!-- .span12 -->
</div><!-- .row-fluid -->
<div class="row-fluid">
	<div class="span9">
		<div class="span7">			
            <?php echo $this->form_step3_ga_3; ?>
		</div><!-- .span7 -->            
		<div class="span5">
			<?php echo $this->partial('partials/_form_grades.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'fieldsAplicable' => $this->fieldsAplicable, 'comments' => $this->comments, 'vectorPoints' => $this->vectorPoints)); ?>
		</div>		
	</div><!-- .span9 -->            
    <div class="span3 final">
        <?php echo $this->partial('partials/_form_results.phtml', array('nrColumnsTotal' => $this->nrColumnsTotal, 'weightingFactor' => $this->weightingFactor, 'maximumPoints' => $this->maximumPoints, 'vectorPoints' => $this->vectorPoints, 'valueOfEachField' => $this->valueOfEachField, 'total_max' => $this->total_max, 'total_pct' => $this->total_pct)); ?>
    </div><!-- .span3 -->            
    <div class="clr"></div>
    <hr>
         <div class="tabbable">
		<?php echo $this->partial('partials/_form_footer_menu.phtml'); ?>
			<div class="tab-content">
			    <div class="tab-pane active" id="tab1">
			    	<h3><?php echo $this->translate('Herramientas'); ?></h3>
			    	<p><?php echo $this->translate('En el caso de utilizar un sistema de depuración in-situ, controlar la calidad del sistema de depuración del agua, evitar el uso de especies invasoras para depuración.'); ?></p>
			    </div>
			    <div class="tab-pane" id="tab2">	
			    	<p><?php echo $this->translate('CTE DB-HS Salubridad.  HS 5: Evacuación de agua.'); ?>			    		
			    	</p>
			    </div>
			    <div class="tab-pane" id="tab3">
			    </div>
				<div class="tab-pane" id="tab4">
			      	<h3><?php echo $this->translate('BREEAM'); ?></h3>
					<p><?php echo $this->translate('Wat 5 Water recycling.'); ?></p>					
					<p><?php echo $this->translate('Recogida de agua de lluvias: '); ?></p>					
					<p><?php echo $this->translate('Tanque con capacidad para recoger el 50% de la recogida en cubierta, o con capacidad para la demanda/ Reutilización del 80% de aguas grises para WC/ Combinación de estrategias.'); ?>
					</p>
					<h3><?php echo $this->translate('LEED'); ?></h3>
					<p><?php echo $this->translate('WE 2 Innovative wastewater technologies.'); ?></p>
					<p><?php echo $this->translate('Reducir el uso de agua potable un 50% respecto al consumo base, o tratar el 50% del agua residual para su uso en el sitio.');?></p>
					<h3><?php echo $this->translate('CASBEE'); ?></h3>
					<p><?php echo $this->translate('LR2 Resources and materials.'); ?>
						<ul>
							<li><?php echo $this->translate('1 Water resources.'); ?></li>
							<li><?php echo $this->translate('1.2 Rainwater and greywater.'); ?>
								<?php echo $this->translate('1.2.1 Rainwater use system. Uso de agua de lluvia para al menos el 20% del consumo total.'); ?>
								<?php echo $this->translate('1.2.2 Grey water use system. No aplicable en apartamentos.'); ?>
							</li>
						</ul>
					</p>
					<h3><?php echo $this->translate('OTROS'); ?></h3>
					<p><?php echo $this->translate('MARM. Sistema de indicadores del agua.'); ?></p>
					<p><a href="http://servicios2.marm.es/sia/indicadores/mapa_indic.jsp" title="http://servicios2.marm.es/sia/indicadores/mapa_indic.jsp" target="_blank">http://servicios2.marm.es/sia/indicadores/mapa_indic.jsp</a></p>					
				</div>
				<div class="tab-pane" id="tab5">
					<p><a href="http://ecometro.org/forums/" title="http://ecometro.org/forums/" target="_blank">http://ecometro.org/forums/</a></p>			      	
				</div>
		</div>
	</div><!-- .tabbable -->
</div><!-- .row-fluid -->
<script type="text/javascript" src="<?php echo $this->serverUrl() . '/skins/ecometro/js/step3/step3functions.js'; ?>"></script>